version: "3.9"
name: "StoreFrontManagement"
services:
  web:
    build:
      context: ./Web
      dockerfile: Dockerfile
    container_name: storef-web
    env_file:
      - ./.env
    volumes:
      - ./Web:/app
      - /app/node_modules
    ports:
      - "${VITE_PORT}:5173"
    command: npm run dev -- --host 0.0.0.0 --port 5173
    networks:
      - app_network

  api:
    build:
      context: ./StoreF
      dockerfile: Dockerfile
    container_name: storef-api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ConnectionStrings__DefaultConnection: >-
        Host=db;Port=5432;Database=${DB_NAME};
        Username=${DB_USER};Password=${DB_PASSWORD}
      Jwt__Secret: ${JWT_SECRET}
      ASPNETCORE_URLS: http://+:8000
    ports:
      - "8000:8000"
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: storef-postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: storef-pgadmin
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: storef-nginx
    restart: unless-stopped
    depends_on:
      - api
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - app_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    driver: bridge
